/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.search.verification.client;

 /*   💚 Mσԃ Bყ Eʅα Oϝϝιƈιαʅ 💛
 *  ❤️ ᴍᴏᴅᴅᴇᴅ ʙʏ ʜᴇᴍᴀɴᴛ ꜱɪɴɢʜ 🔥